import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ModalProvider } from '@/contexts/modalContext'
import { ChurchProvider } from '@/contexts/churchContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ChurchProvider>
          <ModalProvider>{children}</ModalProvider>
        </ChurchProvider>
      </body>
    </html>
  )
}
